import asyncio
from httpx import AsyncClient, ASGITransport
from app.main import app
from app.core.model_router import (
    get_model_router,
    TaskCategory,
    BudgetTier
)

async def test_model_router_flow():
    print("Initializing Dynamic Model Router & Fallback Strategy validation tests...")
    router = get_model_router()

    # 1. Test Task Category Model Routing
    print("\nTest 1: Testing Routing Matrix model selection...")
    dag_route = router.select_model("dag_generation", budget_tier="standard", token_length=5000)
    assert dag_route["primary_model"] == "claude-3-5-sonnet"
    assert dag_route["fallback_model"] == "gpt-4o"

    context_route = router.select_model("context_analysis", budget_tier="standard", token_length=10000)
    assert context_route["primary_model"] == "gemini-1-5-flash"
    assert context_route["fallback_model"] == "llama-3-8b"
    print("SUCCESS: Routing Matrix correctly mapped primary and fallback models per task category.")

    # 2. Test Budget Tier Adjustments
    print("\nTest 2: Testing Budget Tier model routing adjustments...")
    low_budget_dag = router.select_model("dag_generation", budget_tier="low_budget", token_length=5000)
    assert low_budget_dag["primary_model"] == "gemini-1-5-flash"
    print("SUCCESS: Low budget tier routed DAG generation to cost-efficient model.")

    # 3. Test Failover Execution Loop
    print("\nTest 3: Testing Primary -> Fallback failover execution loop...")
    async def mock_failing_primary(model_name: str):
        if "claude" in model_name:
            raise RuntimeError("HTTP 429 Rate limit exceeded on primary model")
        return f"Response generated by fallback model {model_name}"

    exec_res = await router.execute_with_failover("dag_generation", mock_failing_primary)
    assert exec_res["status"] == "SUCCESS_FALLBACK"
    assert exec_res["failover_occurred"] is True
    assert exec_res["model_used"] == "gpt-4o"
    assert "gpt-4o" in exec_res["result"]
    print("SUCCESS: Primary model error triggered automatic failover to GPT-4o.")

    # 4. Test REST API Endpoints
    print("\nTest 4: Testing Model Router HTTP REST API endpoints...")
    transport = ASGITransport(app=app)
    async with AsyncClient(transport=transport, base_url="http://test") as client:
        # GET /api/v1/models/matrix
        res_mat = await client.get("/api/v1/models/matrix")
        assert res_mat.status_code == 200
        assert "dag_generation" in res_mat.json()["routing_matrix"]

        # POST /api/v1/models/route
        res_rt = await client.post(
            "/api/v1/models/route",
            json={
                "task_category": "entity_embeddings",
                "budget_tier": "standard",
                "token_length": 2000
            }
        )
        assert res_rt.status_code == 200
        assert res_rt.json()["primary_model"] == "text-embedding-3-small"
        print("SUCCESS: Model Router REST API endpoints verified.")

    print("\nAll Dynamic Model Router & Fallback Strategy tests completed successfully!")

if __name__ == "__main__":
    asyncio.run(test_model_router_flow())
