"""update agent_memories schema

Revision ID: 0c1bd3401178
Revises: 3032d4dcbbe9
Create Date: 2026-07-18 11:33:47.802056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0c1bd3401178'
down_revision: Union[str, None] = '3032d4dcbbe9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_memories', sa.Column('agent_type', sa.String(length=50), nullable=True))
    op.add_column('agent_memories', sa.Column('key', sa.String(length=255), nullable=True))
    op.add_column('agent_memories', sa.Column('value_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('agent_memories', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('agent_memories', 'embedding',
               existing_type=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agent_memories', 'embedding',
               existing_type=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
               nullable=False)
    op.alter_column('agent_memories', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('agent_memories', 'value_json')
    op.drop_column('agent_memories', 'key')
    op.drop_column('agent_memories', 'agent_type')
    # ### end Alembic commands ###
