"""update workflow definitions and executions schema

Revision ID: 3032d4dcbbe9
Revises: fd6ce13919da
Create Date: 2026-07-18 11:30:11.437903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3032d4dcbbe9'
down_revision: Union[str, None] = 'fd6ce13919da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_executions', sa.Column('workflow_definition_id', sa.UUID(), nullable=True))
    op.add_column('workflow_executions', sa.Column('state_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.alter_column('workflow_executions', 'workflow_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'workflow_executions', 'workflows', ['workflow_definition_id'], ['id'], ondelete='CASCADE')
    op.drop_column('workflow_executions', 'execution_state')
    op.add_column('workflows', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('workflows', sa.Column('dag_structure', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.alter_column('workflows', 'trigger_event',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('workflows', 'dag_definition')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('dag_definition', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.alter_column('workflows', 'trigger_event',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('workflows', 'dag_structure')
    op.drop_column('workflows', 'description')
    op.add_column('workflow_executions', sa.Column('execution_state', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'workflow_executions', type_='foreignkey')
    op.alter_column('workflow_executions', 'workflow_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('workflow_executions', 'state_payload')
    op.drop_column('workflow_executions', 'workflow_definition_id')
    # ### end Alembic commands ###
