"""add fields to agent_executions table

Revision ID: fd6ce13919da
Revises: a68d205e6632
Create Date: 2026-07-18 11:21:55.960762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fd6ce13919da'
down_revision: Union[str, None] = 'a68d205e6632'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_executions', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.add_column('agent_executions', sa.Column('project_id', sa.UUID(), nullable=True))
    op.add_column('agent_executions', sa.Column('agent_role', sa.String(length=100), nullable=True))
    op.add_column('agent_executions', sa.Column('input_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('agent_executions', sa.Column('output_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('agent_executions', sa.Column('execution_time_ms', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'agent_executions', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'agent_executions', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agent_executions', type_='foreignkey')
    op.drop_constraint(None, 'agent_executions', type_='foreignkey')
    op.drop_column('agent_executions', 'execution_time_ms')
    op.drop_column('agent_executions', 'output_payload')
    op.drop_column('agent_executions', 'input_payload')
    op.drop_column('agent_executions', 'agent_role')
    op.drop_column('agent_executions', 'project_id')
    op.drop_column('agent_executions', 'organization_id')
    # ### end Alembic commands ###
