"use client";

import React from "react";
import { Sparkles, Calendar, ArrowRight, CheckCircle2, AlertCircle, ShieldAlert } from "lucide-react";

interface Props {
  onExecuteRecommendation?: (rec: string) => void;
}

export default function AIRecommendationsPanel({ onExecuteRecommendation }: Props) {
  const recommendations = [
    {
      id: 1,
      title: "Rebalance Task Allocation for Dinuka Shavi",
      category: "Task Prioritization",
      impact: "High",
      reason: "Dinuka Shavi is currently operating at 90% story point capacity. Reassigning TPM-105 will reduce burn risk.",
      actionLabel: "Rebalance Workload",
    },
    {
      id: 2,
      title: "Schedule 15-Min Sync for Pull Request #42",
      category: "Meeting Recommendation",
      impact: "Medium",
      reason: "PR #42 has been pending review for 28 hours with 420 additions. A quick sync will prevent sprint spillover.",
      actionLabel: "Schedule Standup",
    },
    {
      id: 3,
      title: "Trigger Automated Knowledge Graph Decay Sweep",
      category: "Architecture Audit",
      impact: "Low",
      reason: "Knowledge Graph has 4 stale implicit edges older than 30 days. Running a sweep optimizes graph traversal.",
      actionLabel: "Run Decay Sweep",
    },
  ];

  return (
    <div className="p-6 rounded-2xl bg-white/5 border border-white/10 backdrop-blur-xl space-y-4 shadow-2xl">
      <div className="flex items-center gap-3">
        <div className="p-3 rounded-xl bg-amber-500/10 text-amber-400 border border-amber-500/20">
          <Sparkles className="w-6 h-6" />
        </div>
        <div>
          <h3 className="text-lg font-bold text-white">Autonomous AI Recommendations</h3>
          <p className="text-xs text-slate-400">Contextual action items generated by the Technical PM Kernel</p>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-4 pt-1">
        {recommendations.map((rec) => (
          <div
            key={rec.id}
            className="p-4 rounded-xl bg-white/5 border border-white/5 hover:border-amber-500/30 transition-all flex flex-col justify-between space-y-3"
          >
            <div>
              <div className="flex items-center justify-between">
                <span className="px-2 py-0.5 rounded text-[10px] font-bold bg-amber-500/10 text-amber-300 border border-amber-500/20">
                  {rec.category}
                </span>
                <span className="text-[10px] font-semibold text-slate-400">Impact: {rec.impact}</span>
              </div>
              <h4 className="text-sm font-bold text-white mt-2">{rec.title}</h4>
              <p className="text-xs text-slate-400 mt-1 line-clamp-3">{rec.reason}</p>
            </div>

            <button
              onClick={() => onExecuteRecommendation && onExecuteRecommendation(rec.title)}
              className="w-full px-3 py-2 rounded-lg bg-amber-500/10 hover:bg-amber-500/20 text-amber-300 text-xs font-semibold border border-amber-500/20 transition-all flex items-center justify-center gap-1.5"
            >
              <span>{rec.actionLabel}</span>
              <ArrowRight className="w-3.5 h-3.5" />
            </button>
          </div>
        ))}
      </div>
    </div>
  );
}
